USE [master]
GO

/****** Object:  Database [EFO]    Script Date: 2025-01-14 11:27:31 ******/
CREATE DATABASE [EFO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EFO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EFO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EFO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EFO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EFO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EFO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EFO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EFO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EFO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EFO] SET ARITHABORT OFF 
GO

ALTER DATABASE [EFO] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EFO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EFO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EFO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EFO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EFO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EFO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EFO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EFO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EFO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EFO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EFO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EFO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EFO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EFO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EFO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EFO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EFO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EFO] SET  MULTI_USER 
GO

ALTER DATABASE [EFO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EFO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EFO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EFO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EFO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EFO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EFO] SET QUERY_STORE = ON
GO

ALTER DATABASE [EFO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EFO] SET  READ_WRITE 
GO

-- Tabeller
USE [EFO]
GO

/****** Object:  Table [dbo].[events]    Script Date: 2025-01-14 12:55:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[events](
	[event_id] [uniqueidentifier] NOT NULL,
	[event_name] [nvarchar](255) NOT NULL,
	[event_date] [datetimeoffset](6) NULL,
	[active] [bit] NOT NULL,
	[description] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[event_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[events] ADD  DEFAULT (newid()) FOR [event_id]
GO

ALTER TABLE [dbo].[events] ADD  DEFAULT ((1)) FOR [active]
GO

ALTER TABLE [dbo].[events] ADD  DEFAULT (NULL) FOR [description]
GO

USE [EFO]
GO

/****** Object:  Table [dbo].[users]    Script Date: 2025-01-14 12:57:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[users](
	[user_id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](255) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[allergies] [varchar](255) NULL,
	[role] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[users] ADD  DEFAULT (newid()) FOR [user_id]
GO

USE [EFO]
GO

/****** Object:  Table [dbo].[participants]    Script Date: 2025-01-14 12:58:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[participants](
	[participant_id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NOT NULL,
	[event_id] [uniqueidentifier] NOT NULL,
	[wants_meal] [bit] NULL,
	[allergies] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[participant_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[participants] ADD  DEFAULT (newid()) FOR [participant_id]
GO

ALTER TABLE [dbo].[participants]  WITH CHECK ADD FOREIGN KEY([event_id])
REFERENCES [dbo].[events] ([event_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[participants]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
ON DELETE CASCADE
GO


-- IIS Apppool användare

USE [EFO]
GO


-- vet inte om det går att skapa login för IIS APPPOOL\EFO eller vad lösenorder 
-- CREATE LOGIN IIS APPPOOL\EFO with password = "Vet inte"

/****** Object:  User [IIS APPPOOL\EFO]    Script Date: 2025-01-14 13:04:42 ******/
CREATE USER [IIS APPPOOL\EFO] FOR LOGIN [IIS APPPOOL\EFO] WITH DEFAULT_SCHEMA=[dbo]
GO


-- Nedan är för dev miljö. För prod ska man nog dra ner på rättigheter.
USE [EFO]
GO

CREATE LOGIN efo_dbo_user with password = 'catSniff!ngKey'

/****** Object:  User [efo_db_user]    Script Date: 2025-01-14 19:16:12 ******/
CREATE USER [efo_db_user] FOR LOGIN [efo_db_user] WITH DEFAULT_SCHEMA=[dbo]
GO

GRANT  SELECT,INSERT,UPDATE,DELETE ON [dbo].[events] TO efo_db_user
GRANT  SELECT,INSERT,UPDATE,DELETE ON [dbo].[users] TO efo_db_user
GRANT  SELECT,INSERT,UPDATE,DELETE ON [dbo].[participants] TO efo_db_user

GRANT CREATE TABLE TO efo_db_user;
