services:
  event-food-orders-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: event-food-orders-db
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - event-food-orders-volume:/var/opt/mssql
    networks:
      - event-food-orders-net
    restart: unless-stopped

  event-food-orders:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-food-orders
    depends_on:
      - event-food-orders-db
    env_file:
       - EventFoodOrders/.env
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    networks:
      - event-food-orders-net
    restart: unless-stopped

volumes:
  event-food-orders-volume:

networks:
  event-food-orders-net:
    driver: bridge
